### ISSUE TITLE
Seems it is not compatible with material-ui v5

### ISSUE THREAD

**Issue by stazcp** [mikbry/material-ui-color#190] opened 2021-12-03 21:45 UTC
Steps to reproduce:
install material UI v5,
install color picker
import Color picker as instructed in the guide

```
Failed to compile
./node_modules/material-ui-color/esm/index.js
Attempted import error: 'StylesProvider' is not exported from '@material-ui/core/styles' (imported as 'v').
```

**Comment by mikbry** [comment] 2021-12-05 19:15
Duplicate of #185

**Closed as completed by mikbry** 2021-12-05 19:15 UTC
